version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong!Passw0rd
    ports:
      - '1433:1433' # Mở port 1433 ra host
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
